# Uncomment the next line to define a global platform for your project
source 'https://github.com/CocoaPods/Specs.git'
 platform :ios, '9.0'

target 'Animals-lv' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks£
  #pod 'Firebase/Core'
  #pod 'Firebase/AdMob'
  #pod 'Google-Mobile-Ads-SDK'
  #use_frameworks!
	



  # Pods for Animals-lv

end
